version: "3.8"
services:
    db:
        image: postgres:15
        container_name: drizzle-postgres
        environment:
            - POSTGRES_PASSWORD=mypassword
            - POSTGRES_DB=drizzle
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
